spring:
  application:
    name: spring-gift
  profiles:
    include: keys

  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
